### ISSUE TITLE
IEmotionServiceClient has internal access

### ISSUE THREAD

**Issue by laurentiustamate94** [Microsoft/Cognitive-Emotion-Windows#10]
Other SDKs, like [Vision](https://github.com/Microsoft/Cognitive-Vision-Windows/blob/master/ClientLibrary/IVisionServiceClient.cs#L46) and [Face](https://github.com/Microsoft/Cognitive-Face-Windows/blob/master/ClientLibrary/IFaceServiceClient.cs#L103) expose the Interface `public`.

Can the EmotionApi do the same to maintain consistency?

**Comment by shawnmclean** [comment]
@chsienki is there an update to this?
