### ISSUE TITLE
.net standard

### ISSUE THREAD

**Issue by andrecarlucci** [Microsoft/Cognitive-Emotion-Windows#17]
Hi guys, 

Any plans to port this to .net standard?

**Comment by SychevIgor** [comment]
@andrecarlucci https://github.com/Microsoft/Cognitive-Emotion-DotNetCore they have also one more repo with the same code (except of rectangle class copied from common library), but I don't think somebody will answer to you and me...

**Comment by cthrash** [comment]
.NET Code standard 1.1 is now supported.
