### ISSUE TITLE
Call the service inside LongRunning Task

### ISSUE THREAD

**Issue by rhalaly** [Microsoft/Cognitive-Emotion-Windows#18]
When call `RecognizeAsync` inside `Task` with `LongRunning` option, the `RecognizeAsync` does not returns.

```
Task.Factory.StartNew(async () => 
{
     EmotionServiceClient service = new EmotionServiceClient(...);
     ...
     await service.RecognizeAsync(...); // Never ends....
}, TaskCreationOptions.LongRunning);
```

I didn't checked `RecognizeInVideoAsync` but I expect the same behavior.

**Comment by cthrash** [comment]
Depending on the threading model of the environment in which you're running your application, you may want to change the threading of your callback.   Specifically, you may want to call `RecognizeAsync(...).ConfigureAwait(false)`.
