### ISSUE TITLE
Exception: "video API has been decomissioned"

### ISSUE THREAD

**Issue by miparnisari** [Microsoft/Cognitive-Emotion-Windows#23]
When trying to run the sample with a video, I see this:

![image](https://user-images.githubusercontent.com/5374887/32534877-6bd09bdc-c40c-11e7-84f9-e6c50eb758e8.png)

Error message: "Video API had been decommissioned from Cognitive Services."

**Comment by cthrash** [comment]
As you may know, this feature has been deprecated.  The sample needs to be updated.

The following is from the official announcement:

**The Video feature of the Emotion API Preview will be retired**
* The Video feature will be retired on October 30, 2017.
* You’ll no longer be able to use the following calls in the Emotion API Preview:
  * POST Emotion Recognition in Video
  * GET Recognition in Video Operation Result

**Recommended actions**
* Update existing code that refers to the above-mentioned functions prior to October 30, 2017.
* To continue using emotion recognition in video, consider the emotion detection capabilities of Azure Media Analytics, a collection of speech and vision components that organizations and enterprises use to get actionable insights from their video files through machine learning technology. To learn more about Media Analytics and its capabilities, please visit the [Media Analytics](https://azure.microsoft.com/en-us/services/media-services/media-analytics) webpage.

**Comment by miparnisari** [comment]
Yeah, I sent an email to the project owners of the ProjectOxford.Emotion NuGet. Hopefully they can fix it on their side?

**Comment by cthrash** [comment]
The new package is [available](https://www.nuget.org/packages/Microsoft.ProjectOxford.Emotion/2.0.40).
