### ISSUE TITLE
Emotion.Scores is always null

### ISSUE THREAD

**Issue by maximgue** [Microsoft/Cognitive-Emotion-Windows#26]
**Context:**
Using:
- .NET Framework 4.6
- Microsoft.ProjectOxford.Emotion 1.0.341
- Microsoft.ProjectOxford.Common 1.0.324
- Newtonsoft.Json 10.0.3

**Problem:**

Calling `EmotionServiceClient.RecognizeAsync` returns an `Emotion[]` array with elements having their `Emotion.FaceRectangle` property properly set.

However `Emotion.Scores` property is always null.

With JSON.NET tracing enabled, we can see:
```
Deserialized JSON: 
[
  {
    "faceRectangle": {
      "height": 129,
      "left": 96,
      "top": 78,
      "width": 129
    },
    "scores": {
      "anger": 5.43854822E-11,
      "contempt": 1.81638086E-07,
      "disgust": 9.657062E-10,
      "fear": 5.90438E-14,
      "happiness": 0.9999829,
      "neutral": 1.6907894E-05,
      "sadness": 5.581749E-10,
      "surprise": 8.70113E-10
    }
  }
]

```

It seems like Emotion.Scores is null because `Microsoft.ProjectOxford.Emotion.Contract.Emotion` class is used.  On the other hand, when using `Microsoft.ProjectOxford.Common.Contract.Emotion` to deserialize the API response, the `scores` property is properly deserialized:
```
void Main()
{
	var test = JsonConvert.DeserializeObject<Microsoft.ProjectOxford.Emotion.Contract.Emotion[]>(apiResponse);
// test.Scores is null
    var test2 = JsonConvert.DeserializeObject<Microsoft.ProjectOxford.Common.Contract.Emotion[]>(apiResponse);
// test2.Scores is not null
}

const string apiResponse= @"[
  {
    ""faceRectangle"": {
      ""height"": 129,
      ""left"": 96,
      ""top"": 78,
      ""width"": 129
    },
    ""scores"": {
	""anger"": 5.43854822E-11,
      ""contempt"": 1.81638086E-07,
      ""disgust"": 9.657062E-10,
      ""fear"": 5.90438E-14,
      ""happiness"": 0.9999829,
      ""neutral"": 1.6907894E-05,
      ""sadness"": 5.581749E-10,
      ""surprise"": 8.70113E-10
	}
  }
]";
```

**Comment by cthrash** [comment]
This issue has been fixed.  Please note that `Emotion.Contract.Emotion` is deprecated in favor of `Common.Contract.Emotion`.  The types were essentially identical, but the latter allowed for better interoperability with the Face SDK.
