### ISSUE TITLE
SampleUserControlLibrary missing from Solution

### ISSUE THREAD

**Issue by marcominerva** [Microsoft/Cognitive-Emotion-Windows#4]
The Solution of the WPF Sample does not contain the SampleUserControlLibrary project, so it cannot be executed.

![missing](https://cloud.githubusercontent.com/assets/3522534/17167815/600c5898-53df-11e6-8ee1-896b3d67e12a.png)

**Comment by cthrash** [comment]
Cognitive-Common-Windows is a git submodule.  Rumor has it that Visual Studio 2015 Update 2 has support for submodules, but you can always `git submodule update` from the command line to clone the common repository if that doesn't work.
