### ISSUE TITLE
error json failed to deserialze in emotionServiceClient.RecognizeInVideoAsync call with a string

### ISSUE THREAD

**Issue by AhmedGS** [Microsoft/Cognitive-Emotion-Windows#5]
Hi all,

I'm trying to call the emotionServiceClient.RecognizeInVideoAsync call with a string (as it's one of its overloaded functions) but it doesn't work. When I look a the package using "Telerik Fiddler" I get:
{"error":{"code":"BadArgument","message":"Failed to deserialize JSON request."}}

Also when I use emotionServiceClient.RecognizeAsync with a similar string (but for an image) it work without problem.

Can you help?

Thanks,
Ahmed

**Comment by cthrash** [comment]
What does the request body look like in Fiddler?  It should like something like the following: `{"url":"http://example.com/video.mp4"}`

**Comment by AhmedGS** [comment]
When I write it like this json you mentioned, and I check with Fiddler I get all the escape sequence inside like: "{ \"url\":\"http://blablabla.blob.core.windows.net/testblob/16040916553300010057_SH-MARJ-02.wmv\"}".

What should I do?

**Comment by cthrash** [comment]
The design was to pass a URL, but due to a bug (fixed in this repo, but not yet in NuGet) the JSON was malformed.  If you're using the NuGet package, the temporary hack is pass the JSON in the place of the URL string.

**Comment by KevinYao0428** [comment]
Hi, I am trying to debug the WPF project "EmotionAPI-WPF-Samples" in Visual Studio 2015, When I opened it, the SampleUserControlLibrary couldn't be loaded. Anyone knows that what it is wrong?

**Comment by oliverwm** [comment]
Hi Kevin, this seems like a different issue, but did you pull in the submodules when you cloned the repository? Steps 2 & 3 in the readme contain the "git submodule" commands you should execute before opening the code in Visual Studio.

**Comment by cthrash** [comment]
Please reactivate if this issue remains unresolved.
