### ISSUE TITLE
Project can't be loaded

### ISSUE THREAD

**Issue by burakbilgehan** [Microsoft/Cognitive-Emotion-Windows#7]
Hello, I used this page (https://www.microsoft.com/cognitive-services/en-us/emotion-api/documentation/getstarted) as a referance and tried to execute each step as it's written.

But soon as I opened the project in Visual studio it gives an error:

> One or more projects in the solution were not loaded correctly. Please see the Output Window for details.

After clicking okay, trying to ignore the issue, I go to the next step, Managing NuGet Packages. When I try to install Newtonsoft.Json, it said that it's already installed, but i can still upgrade it. I go on to the next step with both updating, and non-updating methods. 

Next step is building and running the solution.  When I build it, i see 2 errors, 5 warnings.

Errors:

1. Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'VideoResultControl' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 28 Position 10.	EmotionAPI-WPF-Samples	C:\Users\kaanb\Desktop\Cognitive-Emotion-Windows-master\Sample-WPF\EmotionDetectionUsingVideoPage.xaml	28	

2. Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'SampleScenarios' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 12 Position 10.	EmotionAPI-WPF-Samples	C:\Users\kaanb\Desktop\Cognitive-Emotion-Windows-master\Sample-WPF\MainWindow.xaml	12	

Warnings:

1. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'SampleUserControlLibrary' could not be found.	EmotionAPI-WPF-Samples			

2. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced project '..\Cognitive-Common-Windows\SampleUserControlLibrary\SampleUserControlLibrary.csproj' does not exist.	EmotionAPI-WPF-Samples			

3. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced project '..\Cognitive-Common-Windows\SampleUserControlLibrary\SampleUserControlLibrary.csproj' does not exist.	EmotionAPI-WPF-Samples			

4. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The tag 'VideoResultControl' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 28 Position 10.	EmotionAPI-WPF-Samples	C:\Users\kaanb\Desktop\Cognitive-Emotion-Windows-master\Sample-WPF\EmotionDetectionUsingVideoPage.xaml	28	

5. Severity	Code	Description	Project	File	Line	Suppression State
Warning		The tag 'SampleScenarios' does not exist in XML namespace 'clr-namespace:SampleUserControlLibrary;assembly=SampleUserControlLibrary'. Line 12 Position 10.	EmotionAPI-WPF-Samples	C:\Users\kaanb\Desktop\Cognitive-Emotion-Windows-master\Sample-WPF\MainWindow.xaml	12	

As you can predict, I cannot run this program after that. It should be running and asking me for the activation code, to advance.

Can you help me?

**Comment by phys94** [comment]
The missing component can be found in below link:

https://github.com/Microsoft/ProjectOxford-ClientSDK/tree/master/SampleUtil
